In [ ]:
# Regularisation
# -> technique to prevent overfitting in regression models
# -> adds a penalty term to the models
# -> adds weights -> some features large weights, fluctutating weights - adds penalty to those features
# -> controls large coeffs
# -> regularisation paramter lambda * Penalty
# CW + Lambda * Penalty
# Lambda = 0 -> ordinary regression
# Lambda is too large -> coeff shrinks almost towards 0

In [ ]:
# Types 
# Lasso Regression - L1 Regularisation
# Ridge Regression - L2 Regularisation

In [ ]:
# Lasso Regression - L1 Regularisation
# -> Least Absolute Shrinkage and Selection Operator
# -> used for regularisation
# -> feature selection : many features, model becomes too complex, reduce features : important features
#                      -> eliminate irrelavant features
# parameter - alpha

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('Hitters.csv')
df.head()

,Unnamed: 0,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,-Andy Allanson,293,66,1,30,29,14,1,293,66,...,30,29,14,A,E,446,33,20,NaN,A
1,-Alan Ashby,315,81,7,24,38,39,14,3449,835,...,321,414,375,N,W,632,43,10,475.0,N
2,-Alvin Davis,479,130,18,66,72,76,3,1624,457,...,224,266,263,A,W,880,82,14,480.0,A
3,-Andre Dawson,496,141,20,65,78,37,11,5628,1575,...,828,838,354,N,E,200,11,3,500.0,N
4,-Andres Galarraga,321,87,10,39,42,30,2,396,101,...,48,46,33,N,E,805,40,4,91.5,N

In [5]:
# Remove Unnamed column
df.drop('Unnamed: 0', axis=1, inplace=True) # axis=1 - remove column, inplace=True -> remove from original dataframe

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   AtBat      322 non-null    int64
 1   Hits       322 non-null    int64
 2   HmRun      322 non-null    int64
 3   Runs       322 non-null    int64
 4   RBI        322 non-null    int64
 5   Walks      322 non-null    int64
 6   Years      322 non-null    int64
 7   CAtBat     322 non-null    int64
 8   CHits      322 non-null    int64
 9   CHmRun     322 non-null    int64
 10  CRuns      322 non-null    int64
 11  CRBI       322 non-null    int64
 12  CWalks     322 non-null    int64
 13  League     322 non-null    object
 14  Division   322 non-null    object
 15  PutOuts    322 non-null    int64
 16  Assists    322 non-null    int64
 17  Errors     322 non-null    int64
 18  Salary     263 non-null    float64
 19  NewLeague  322 non-null    object
dtypes: float64(1), int64(16), object(3)
memory usage: 50.4+ KB

In [9]:
# convert categorical into numerical
dummies = pd.get_dummies(df[['League','Division','NewLeague']])
dummies = dummies.astype(int)
dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   League_A     322 non-null    int32
 1   League_N     322 non-null    int32
 2   Division_E   322 non-null    int32
 3   Division_W   322 non-null    int32
 4   NewLeague_A  322 non-null    int32
 5   NewLeague_N  322 non-null    int32
dtypes: int32(6)
memory usage: 7.7 KB

In [11]:
dummies.head()

   League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
0         1         0           1           0            1            0
1         0         1           0           1            0            1
2         1         0           0           1            1            0
3         0         1           1           0            0            1
4         0         1           1           0            0            1

In [15]:
# Features and Target
y = df['Salary']
X_numerical = df.drop(['League','Division','NewLeague','Salary'],axis=1)
X_numerical.info()
# X will be concatentaion of numerical and dummies

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   AtBat    322 non-null    int64
 1   Hits     322 non-null    int64
 2   HmRun    322 non-null    int64
 3   Runs     322 non-null    int64
 4   RBI      322 non-null    int64
 5   Walks    322 non-null    int64
 6   Years    322 non-null    int64
 7   CAtBat   322 non-null    int64
 8   CHits    322 non-null    int64
 9   CHmRun   322 non-null    int64
 10  CRuns    322 non-null    int64
 11  CRBI     322 non-null    int64
 12  CWalks   322 non-null    int64
 13  PutOuts  322 non-null    int64
 14  Assists  322 non-null    int64
 15  Errors   322 non-null    int64
dtypes: int64(16)
memory usage: 40.4 KB

In [17]:
# X will be concatentaion of numerical and dummies
X = pd.concat([X_numerical, dummies], axis=1)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AtBat        322 non-null    int64
 1   Hits         322 non-null    int64
 2   HmRun        322 non-null    int64
 3   Runs         322 non-null    int64
 4   RBI          322 non-null    int64
 5   Walks        322 non-null    int64
 6   Years        322 non-null    int64
 7   CAtBat       322 non-null    int64
 8   CHits        322 non-null    int64
 9   CHmRun       322 non-null    int64
 10  CRuns        322 non-null    int64
 11  CRBI         322 non-null    int64
 12  CWalks       322 non-null    int64
 13  PutOuts      322 non-null    int64
 14  Assists      322 non-null    int64
 15  Errors       322 non-null    int64
 16  League_A     322 non-null    int32
 17  League_N     322 non-null    int32
 18  Division_E   322 non-null    int32
 19  Division_W   322 non-null    int32
 20  NewLeague_A  322 non-null    int32
 21  NewLeague_N  322 non-null    int32
dtypes: int32(6), int64(16)
memory usage: 47.9 KB

In [21]:
# fill salary missing values
median_salary = y.median(skipna=True)
y = y.fillna(median_salary)
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 322 entries, 0 to 321
Series name: Salary
Non-Null Count  Dtype
--------------  -----
322 non-null    float64
dtypes: float64(1)
memory usage: 2.6 KB

In [23]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Lasso works well when values are standarized
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()  # works internally with mean and std deviation
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
# Create Lasso Model

lasso_model = Lasso(alpha=1, max_iter=10000).fit(X_train_scaled, y_train)
print("Lasso Intercept :",lasso_model.intercept_)
print("Lasso Coeffs : ",lasso_model.coef_)

Lasso Intercept : 506.93387937743194
Lasso Coeffs :  [-2.91366408e+02  2.45787153e+02  2.53134379e+01 -0.00000000e+00
 -9.16813158e+00  1.06494342e+02 -6.30999382e+01 -2.64071124e+02
  2.18699586e+02  0.00000000e+00  2.39075832e+02  2.36492688e+02
 -1.99714384e+02  4.56957489e+01  3.56783836e+01 -1.46911893e+01
 -1.57094520e+01  0.00000000e+00  5.15603911e+01 -0.00000000e+00
  3.52822162e+00 -1.01743084e-14]

In [ ]:
# positive -> increase feature value - salary will also increase
# negative -> increase feature value - salary will decrease
# magnitude -> show strength of feature. Larger magnitude, larger strength

In [51]:
# Prediction and Evaluation
y_test_pred = lasso_model.predict(X_test_scaled)

# Evaluation - rmse, r2 score
print("Testing Data RMSE : ",np.sqrt(mean_squared_error(y_test, y_test_pred)))
print("Testing Data R2 Score : ",r2_score(y_test, y_test_pred))

Testing Data RMSE :  351.64951546148677
Testing Data R2 Score :  0.35650395596332163

In [55]:
# to further improve we can use LassoCV model

from sklearn.linear_model import LassoCV

lasso_cv_model = LassoCV(alphas=np.random.randint(0,1000,100), cv=10, max_iter=10000, n_jobs=-1).fit(X_train_scaled, y_train)
lasso_cv_model.alpha_

3

In [57]:

lasso_model = Lasso(alpha=3, max_iter=10000).fit(X_train_scaled, y_train)
print("Lasso Intercept :",lasso_model.intercept_)
print("Lasso Coeffs : ",lasso_model.coef_)

# Prediction and Evaluation
y_test_pred = lasso_model.predict(X_test_scaled)

# Evaluation - rmse, r2 score
print("Testing Data RMSE : ",np.sqrt(mean_squared_error(y_test, y_test_pred)))
print("Testing Data R2 Score : ",r2_score(y_test, y_test_pred))

Lasso Intercept : 506.9338793774319
Lasso Coeffs :  [-2.41304768e+02  2.18214881e+02  9.77841058e+00  0.00000000e+00
  0.00000000e+00  9.37419095e+01 -7.27481691e+01 -0.00000000e+00
  2.17555446e+01  0.00000000e+00  1.78265888e+02  2.08700275e+02
 -1.70364276e+02  4.25286653e+01  1.70243629e+01 -6.11892675e+00
 -9.09087611e+00  0.00000000e+00  5.21890645e+01 -6.63541854e-15
  0.00000000e+00 -0.00000000e+00]
Testing Data RMSE :  347.2659027914624
Testing Data R2 Score :  0.37244741790603275